TeckTalkTimeTable/TeckTalkTimeTable/Controllers/TopicCommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TeckTalkTimeTable.Models;

namespace TeckTalkTimeTable.Controllers
{
    public class TopicCommentController : Controller
    {
        
            private UsersContext db = new UsersContext();
            public ActionResult index()
            {
                var topicCommentData = db.TopicComment.ToList();
                return PartialView("_TopicCommentList", topicCommentData);
            }

            public ActionResult Create()
            {
                return PartialView("_Create");
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Create(TopicComment comment)
            {
                if (ModelState.IsValid)
                {
                    db.TopicComment.Add(comment);
                    db.SaveChanges();
                    var updatedtopicComment = db.TopicComment.ToList<TopicComment>();

                    return PartialView("_TopicCommentList", updatedtopicComment);
                }

                return View(comment);
            }

            public ActionResult Edit(int id = 0)
            {
                TopicComment editComment = db.TopicComment.Find(id);
                if (editComment == null)
                {
                    return PartialView(HttpNotFound());
                }
                return PartialView("_Edit", editComment);
            }

            //
            // POST: /Topics/Edit/5

            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit(TopicComment comment)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(comment).State = EntityState.Modified;
                    db.SaveChanges();
                    var updatedComments = db.TopicComment.ToList<TopicComment>();
                    return PartialView("_TopicCommentList", updatedComments);
                }
                return View(comment);
            }

            public ActionResult Delete(int id = 0)
            {
                TopicComment comment = db.TopicComment.Find(id);
                if (comment != null)
                {
                    db.TopicComment.Remove(comment);
                    db.SaveChanges();

                }
                var updatedComment = db.TopicComment.ToList<TopicComment>();
                return PartialView("_TopicCommentList", updatedComment);
            }
        }
    
}

TeckTalkTimeTable/TeckTalkTimeTable/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeckTalkTimeTable.Filters;
using TeckTalkTimeTable.Models;
using WebMatrix.WebData;
using TeckTalkTimeTable.Repository;

namespace TeckTalkTimeTable.Controllers
{
    [InitializeSimpleMembership] 
    public class TopicsController : Controller   {

        private TecTalkUow Uow = new TecTalkUow();
        
       
        //
        // GET: /Topics/
        [LogWrite]
        public ActionResult Index()
        {
            Console.Write("faceffsffff");
          return PartialView("_TopicList", Uow.Users.getUsersHasUpComingTopic());
          
        }
             
        //
        // GET: /Topics/Create

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        // kat 
        // POST: /Topics/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Topics topics)
        {
            topics.userID = WebSecurity.CurrentUserId;
            if (ModelState.IsValid)
            {
                Uow.bace.Add<Topics>(topics);
                Uow.Commit();


                return PartialView("_TopicList", Uow.Users.getUsersHasUpComingTopic());
          
            }

            return PartialView("_Create",topics);
        }

        //
        // GET: /Topics/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Topics topics = Uow.bace.Query<Topics>().Single(r => r.id == id);
            if (topics == null)
            {
                return PartialView(HttpNotFound());
            }
            return PartialView("_Edit", topics);
        }

        //
        // POST: /Topics/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Topics topics)
        {
            if (ModelState.IsValid)
            {
                Uow.bace.Update<Topics>(topics);
                Uow.Commit();


                return PartialView("_TopicList", Uow.Users.getUsersHasUpComingTopic());
          
            }
            return View(topics);
        }

        //
        // GET: /Topics/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Topics topics = Uow.bace.Query<Topics>().Single(r => r.id == id);
            if (topics != null)
            {
                Uow.bace.Remove<Topics>(topics);
                Uow.Commit(); 
                
            }


            return PartialView("_TopicList", Uow.Users.getUsersHasUpComingTopic());
          
        }

        //
        // POST: /Topics/Delete/5

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Topics topics = db.Topics.Find(id);
        //    db.Topics.Remove(topics);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //
        // GET: /Topics/Details/5

        public ActionResult Details(int id = 0)
        {
            Topics topics = Uow.bace.Query<Topics>().Single(r => r.id == id);
            if (topics == null)
            {
                return HttpNotFound();
            }
            return View(topics);
        }

        protected override void Dispose(bool disposing)
        {
            Uow.bace.Dispose();
            base.Dispose(disposing);
        }
    }
}

TeckTalkTimeTable/TeckTalkTimeTable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "index", "Topics", null, new { id = "homes" })</li>
                        <li>@Html.ActionLink("Add Topic", "Create", "Topics", null, new { id = "add_topic" })</li>
                        <li>@Html.ActionLink("Comment", "index", "TopicComment", null, new { id = "add_topicComment" })</li>
                         
                        <li>@Html.ActionLink("Question", "CreateQuestion", "Question", null, new { id = "add_question" })</li>
                        <li>@Html.ActionLink("Add Topic Comment", "Create", "TopicComment", null, new { id = "add_topicComment" })</li>

                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>