TeckTalkTimeTable/TeckTalkTimeTable/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TeckTalkTimeTable.Models
{
    public class Question
    {
        public int QuestionID { get; set; }
        
        [Required]
        [DataType(DataType.Text)]
        public string Catogary { get; set; }
        
        [Required]
        [DataType(DataType.Text)]
        [StringLength(maximumLength: 200, MinimumLength = 5)]
        [DisplayName("Question Title")]
        public string QuestionTitle { get; set; }
       
        [Required]
        [DataType(DataType.MultilineText)]
        [DisplayName("Questions to Discuss")]
        public string QuestionToAsk { get; set; }
       
        [DataType(DataType.DateTime)]
        [DisplayName("Created Date")]
        public DateTime CreatedDate { get; set; }
       
        [DataType(DataType.Text)]
        public string UserName { get; set; }
        [DisplayName("Likes for the Question")]
        public int? NoOfLikesforTheQuestion { get; set; }
    }
}

TeckTalkTimeTable/TeckTalkTimeTable/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TeckTalkTimeTable.Models;

namespace TeckTalkTimeTable.Controllers
{
    public class QuestionController : Controller
    {
        //
        // GET: /Question/
    

        public ActionResult Index()
        {
            var db = new UsersContext();
            var question = db.Questions.ToList<Question>();

            return PartialView("_Index", question);
        }

        #region CreateQuestion
        [HttpGet]
        public ActionResult CreateQuestion()
        {
            
            var catagoryList = new SelectList(new[] { "Technical", "NonTechnical", "Other" });
            ViewBag.CategoryList = catagoryList;
            return PartialView("_CreateQuestion");
        }

        [HttpPost]
        public ActionResult CreateQuestion([Bind(Exclude = "NoOfLikesforTheQuestion")] Models.Question question)
        {
            question.CreatedDate = DateTime.Now;
            question.UserName = Membership.GetUser().UserName.ToString();

            if (ModelState.IsValid)
            {
                var db = new UsersContext();
                db.Questions.Add(question);
                db.SaveChanges();
                var questions = db.Questions.ToList<Question>();
                return PartialView("_Index", questions);
            }
            return CreateQuestion();
        }
        #endregion

        #region Edit
        /// <summary>
        /// get the selected item id and show edit form
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id = 0)
        {
            var catagoryList = new SelectList(new[] { "Technical", "NonTechnical", "Other" });
            ViewBag.CategoryList = catagoryList;
            var db = new UsersContext();
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return PartialView(HttpNotFound());
            }
            return PartialView("_Edit", question);
        }

       
        /// <summary>
        /// if the editeed datea is valid to the model Question 
        /// update the database
        /// </summary>
        /// <param name="question"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            question.CreatedDate = DateTime.Now;
            question.UserName = Membership.GetUser().UserName.ToString();
            if (ModelState.IsValid)
            {
                var db = new UsersContext();
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                var updaQuestion = db.Questions.ToList<Question>();
                return PartialView("_Index", updaQuestion);
            }
            return PartialView("_Index");
        }
        #endregion

        #region Delete
        public ActionResult Delete(int id = 0)
        {
             var db = new UsersContext();
            Question question = db.Questions.Find(id);
            if (question != null)
            {
                db.Questions.Remove(question);
                db.SaveChanges();

            }
            var deleteRow = db.Questions.ToList<Question>();
            return PartialView("_Index", deleteRow);
        }
        #endregion
    }
}

TeckTalkTimeTable/TeckTalkTimeTable/Views/Question/_CreateQuestion.cshtml
@model TeckTalkTimeTable.Models.Question

<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@using (Html.BeginForm("CreateQuestion", "Question", FormMethod.Post, new { id = "datss", @data_ttt_ajax = "true" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Question</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Catogary)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Catogary,(SelectList)ViewBag.CategoryList)
            @Html.ValidationMessageFor(model => model.Catogary)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.QuestionTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QuestionTitle)
            @Html.ValidationMessageFor(model => model.QuestionTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QuestionToAsk)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QuestionToAsk)
            @Html.ValidationMessageFor(model => model.QuestionToAsk)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoOfLikesforTheQuestion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoOfLikesforTheQuestion)
            @Html.ValidationMessageFor(model => model.NoOfLikesforTheQuestion)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<script>
    $(function () {

        var ajaxFormSubmit = function () {
            var $form = $(this);

            var options = {
                url: $form.attr("action"),
                type: $form.attr("method"),
                data: $form.serialize()
            };

            $.ajax(options).done(function (data) {
                var $target = $("#dynamic_content");
                var $newHtml = $(data);
                $target.replaceWith($newHtml);
               
            });

            return false;
        };    

        $("form").submit(ajaxFormSubmit);

    });
</script>

TeckTalkTimeTable/TeckTalkTimeTable/Views/Question/_Edit.cshtml
@model TeckTalkTimeTable.Models.Question

<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@using (Html.BeginForm("CreateQuestion", "Question", FormMethod.Post, new { id = "datss", @data_ttt_ajax = "true" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Question</legend>

        @Html.HiddenFor(model => model.QuestionID)

       <div class="editor-label">
            @Html.LabelFor(model => model.Catogary)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Catogary,(SelectList)ViewBag.CategoryList)
            @Html.ValidationMessageFor(model => model.Catogary)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QuestionTitle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QuestionTitle)
            @Html.ValidationMessageFor(model => model.QuestionTitle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QuestionToAsk)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QuestionToAsk)
            @Html.ValidationMessageFor(model => model.QuestionToAsk)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreatedDate)
        </div>
       @* <div class="editor-field">
            @Html.EditorFor(model => model.CreatedDate)
            @Html.ValidationMessageFor(model => model.CreatedDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.NoOfLikesforTheQuestion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoOfLikesforTheQuestion)
            @Html.ValidationMessageFor(model => model.NoOfLikesforTheQuestion)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<script>
    $(function () {

        var ajaxFormSubmit = function () {
            var $form = $(this);

            var options = {
                url: $form.attr("action"),
                type: $form.attr("method"),
                data: $form.serialize()
            };

            $.ajax(options).done(function (data) {
                var $target = $("#dynamic_content");
                var $newHtml = $(data);
                $target.replaceWith($newHtml);
                
            });

            return false;
        };    

        $("form").submit(ajaxFormSubmit);

    });
</script>

TeckTalkTimeTable/TeckTalkTimeTable/Views/Question/_Index.cshtml
@model IEnumerable<TeckTalkTimeTable.Models.Question>

<div id="dynamic_content">

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Catogary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuestionTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuestionToAsk)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoOfLikesforTheQuestion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Catogary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuestionTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuestionToAsk)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoOfLikesforTheQuestion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.QuestionID }, new { id="edit_question" }) |
             @Html.ActionLink("Delete", "Delete", new { id=item.QuestionID }, new { id="delete_question" })
        </td>
    </tr>
}

</table>
    </div>